function card1(){
    alert("Hello World");
 }

 function card2(){
    document.getElementById("card2ID").innerHTML="javaScrip can change content of HTML";
 }

 function card3(){
    let now = new Date;
    
    let hour = now.getHours();
    hour = (now==0) ? 12:((hour>12)?(hour-12):hour);
    hour = (hour<10) ? "0"+hour: hour;
    
    let min = now.getMinutes();
    min = (min<10)? "0"+min:min;
    
    let sec = now.getSeconds();
    sec = (sec<10)?"0"+sec:sec;
    
       var midday = (hour>=12)? "PM":"AM";

    document.getElementById("card3ID").innerHTML=hour+":"+min+":"+sec+" "+midday;
    


     
    
    let day = now.getDate();
    let weekday = now.getDay();
    let days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
    let nameOfDay = days[weekday];
    
    let month = now.getMonth();
    let months = ["January","February","March","April","May","June","July","Augest","September","October","November","December"];
    let nameOfMonth = months[month];

    let year = now.getFullYear();
    document.getElementById("card3ID2").innerHTML = day+"("+nameOfDay+")"+"/"+(month+1)+"("+nameOfMonth+")"+"/"+year;
 
 }

 setInterval(card3,1000);

 
 function card4B1(){
        let webBody = document.body;
        webBody.style.backgroundColor="black";
    }

function card4B2(){
    let fontStyle = document.getElementById("card4ID");
    fontStyle.style.fontFamily="Sue Ellen Francisco";
}

function card4B3(){
    let fontSize = document.getElementById("card4ID");
    fontSize.style.fontSize="30px";
}

function card4B4(){
    let fontColor = document.getElementById("card4ID");
    fontColor.style.color="red";
}

function card4B5(){
    let btnColor = document.getElementById("b4");
    btnColor.style.backgroundColor="green";
}

function card4B6(){
    if(document.getElementById("card4ID_NEW")){
        alert("Already created!!!");
    }else{
        let tagP=document.createElement("p");
        tagP.setAttribute("id","card4ID_NEW");
        let text = document.createTextNode("This p tag is generated by javaScript");
        tagP.appendChild(text);
        let div = document.getElementById("waiting");
        div.appendChild(tagP);
    }
}

function card4B7(){
    let p = document.getElementById("card4ID_NEW");
    p.style.color="gold";
    p.style.fontSize="30px";
}


function play(){
    var audio = document.getElementById("ply");
    audio.play();
}
function pause(){
    var audio = document.getElementById("ply");
    audio.pause();
}
function stop(){
    var audio = document.getElementById("ply");
    audio.pause();
    audio.currentTime=0;
}


function playVideo(){
    var video =document.getElementById("plyV");
    video.play();
}
function pauseVideo(){
    var video =document.getElementById("plyV");
    video.pause();
}
function stopVideo(){
    var video =document.getElementById("plyV");
    video.pause();
    video.currentTime=0;
}

function changeGif1(){
    let g1 = document.getElementById("img7");
    let g2 = document.getElementById("img8");

    g1.setAttribute("src","gif/8.gif");
    g2.setAttribute("src","gif/7.gif");
}
function changeGif2(){
    let g1 = document.getElementById("img7");
    let g2 = document.getElementById("img8");

    g1.setAttribute("src","gif/7.gif");
    g2.setAttribute("src","gif/8.gif");
}


function cal(){
    var f = document.getElementById("f").value;
    var c = document.getElementById("c").value;

    var calF = (c*(9/5))+32;
    var calC = (f-32)*(5/9);

    if(c == ""){
        document.getElementById("c").value=calC+'\u2103';
    }

    if(f == ""){ 
        document.getElementById("f").value=calF+'\u2109';
    }
    
}
function clearInput(){
    document.getElementById("f").value="";
    document.getElementById("c").value="";
}


function hideAll(){
   let elements = document.querySelectorAll('*:not(#card9):not(#img9):not(#b11):not(#b12)');
   for(var i = 0; i < elements.length; i++){
        elements[i].style.visibility="hidden";
    }
}
function showAll(){
    let elements = document.querySelectorAll('*');
    for(var i = 0; i < elements.length; i++){
        elements[i].style.visibility="visible";
    }
}

var generate='';
function GenerateCode(){
    var length=8;
    var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!@#$%^&*()_+{}[]/\<>.,';
    let name = document.getElementById("name").value;
    if(name==""){
        alert("You should have a name......");
    }else{
        for(var i=0; i<length; i++){
            generate+=characters.charAt(Math.floor(Math.random()* characters.length));
        }
        console.log(generate);
    }
}

function nextChapter(){
    let h = document.getElementById("hiddenCode").value;
    let name = document.getElementById("name").value;
    
    if(h==generate){
        localStorage.setItem("send",name);
        window.location="/newWelcome";
    }else{
        alert("hidden code is wrong"); 
    }
}

//popup 1
function popup1(){
     // Calculate the center position of the screen
     var screenWidth = window.screen.availWidth;
     var screenHeight = window.screen.availHeight;
     var popupWidth = 1000;
     var popupHeight = 600;
     var leftPosition = (screenWidth - popupWidth) / 2 + window.screenX;
     var topPosition = (screenHeight - popupHeight) / 2 + window.screenY;
 
     // Create the popup window
     var popupWindow = window.open("", "popup", "width=1000,height=600,left=" + leftPosition + ",top=" + topPosition);
 
     // Show the web view inside the popup window
     var iframe = popupWindow.document.createElement("iframe");
     iframe.setAttribute("src", "https://binaryplanetaz.blogspot.com/");
     iframe.style.width = "100%";
     iframe.style.height = "100%";
     popupWindow.document.body.appendChild(iframe);
}